### ISSUE TITLE
Signed tags?

### ISSUE THREAD

**Issue by SantiagoTorres** [romis2012/aiohttp-socks#11]
I'd love to verify signatures over your releases when building python-aiohttp-socks for arch (and I suspect other people would also like to do that). Would it be possible to have your release tags signed with a key you control?

Cheers!

**Comment by NotoriousRebel** [comment]
@SantiagoTorres any updates on this?

**Comment by SantiagoTorres** [comment]
No, I unfortunately never heard back from anybody...

**Comment by romis2012** [comment]
The v0.3.9 is signed
