### ISSUE TITLE
Resolving hostname to ipv6

### ISSUE THREAD

**Issue by avdolgushev** [romis2012/aiohttp-socks#16]
The network I am working in allows only ipv6 connections but it doesn't work when I create ProxyConnector with host parameter as domain. 
I tried to pass family=socket.AF_INET6 to **ProxyConnector** but it didn't helped. It happens because BaseProxy doesn't use family (it is marked as deprecated) and when **_resolve_proxy_host** is called it calls **resolve** without specifying family and the default socket.AF_INET is used. 
I patched the default family value to socket.AF_INET6 and it helped me. 
Do you think that family parameter of ProxyConnector should be used during resolving hostname?

**Comment by romis2012** [comment]
I changed the default value of the family parameter to AF_UNSPEC, your host should resolved correctly now

**Comment by avdolgushev** [comment]
It helped.
Thank you!
