### ISSUE TITLE
First socks request takes much more time when compared to other requests

### ISSUE THREAD

**Issue by bokklu** [romis2012/aiohttp-socks#17]
I've noticed that the first request always takes much more time when compared to the later requests of the same session. Below is the code to reproduce this behaviour:

```
async def connect(session, url):
    for i in range(10):
        try:
            start_time = time.time()
            async with async_timeout.timeout(7):
                async with session.get(url) as response:
                    print(f'Request {i} {int(round((time.time() - start_time) * 1000))}ms')
        except asyncio.TimeoutError:
            continue
        except Exception as ex:
            print(ex)
            continue

async def fetch_socks():
    connector = ProxyConnector.from_url('socks4://91.246.213.104:4145')
    async with aiohttp.ClientSession(connector=connector) as session:
        await connect(session, 'http://example.com')

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(fetch_socks())
```

Output is the following:
![image](https://user-images.githubusercontent.com/26428189/82761672-86f8e780-9dfc-11ea-8cdd-6f74a48a75b4.png)

Is this the intended behaviour?

I've tested this behaviour with the normal aiohttp library with http proxies, and it doesn't happen?

**Comment by romis2012** [comment]
> Is this the intended behaviour?

Yes, in your case aiohttp creates a connection to the proxy server only once on the first request.
