### ISSUE TITLE
Http proxy ignores User Agent when connects

### ISSUE THREAD

**Issue by avdolgushev** [romis2012/aiohttp-socks#19]
Hi!

Some websites don't allow connections with python default user agent (such as "Python/3.8 aiohttp/3.6.2"). I can't specify another user agent since http proxy ignores it and sets the default SERVER_SOFTWARE at line 33 in http_proxy.py
It could be solved by using passed user agent in req parameter to _wrap_create_connection function in connector.py

Thank you!

**Comment by romis2012** [comment]
> Some websites don't allow connections with python default user agent...

Some websites or some proxies?
What is purpose to pass user agent when connect to proxy?

**Comment by avdolgushev** [comment]
Sorry, it was a mistake. You are right that that user agent is passed only when connects to proxy, not to webserver.
