### ISSUE TITLE
Since your last update - Cannot import name 'SocksConnector' from 'aiohttp_socks'

### ISSUE THREAD

**Issue by venomone** [romis2012/aiohttp-socks#20]
### 
Since your last update I'm getting the following error with electrum-dash and electrum-ltc it seems?:

> Traceback (most recent call last):
>   File "/usr/local/bin/electrum-dash", line 82, in <module>
>     from electrum_dash.logging import get_logger, configure_logging
>   File "/usr/local/lib/python3.8/site-packages/electrum_dash/__init__.py", line 2, in <module>
>     from .util import format_satoshis
>   File "/usr/local/lib/python3.8/site-packages/electrum_dash/util.py", line 45, in <module>
>     from aiohttp_socks import SocksConnector, SocksVer
> ImportError: cannot import name 'SocksConnector' from 'aiohttp_socks' (/usr/local/lib/python3.8/site-packages/aiohttp_socks/__init__.py)

please also see: https://github.com/pooler/electrum-ltc/issues/243, https://github.com/akhavr/electrum-dash/issues/124
Any idea?

**Comment by romis2012** [comment]
SocksConnector was deprecated in ver 0.3.3 and removed in ver 0.5.0. You should use ProxyConnector or pin your dependencies to the 0.4.* (not recommended).

**Comment by romis2012** [comment]
SocksConnector is available again in v0.5.2

**Comment by venomone** [comment]
Hello,

thanks for your fast reply, and your fix, works like a charm :+1:
