### ISSUE TITLE
Headers is not transmited?

### ISSUE THREAD

**Issue by victor-ab** [romis2012/aiohttp-socks#32]
Hi! I am trying to use an API key to authenticate. 

Works well without the proxy connector. But when I plug it in, the sever says it is not authenticated.

```python
import asyncio

headers = {
    "Accept": "application/json",
    "API-KEY": "MY-KEY"
}
async def fetch(url):
    connector = ProxyConnector.from_url(proxy_url, rdns=True)

    async with aiohttp.ClientSession(connector=connector,headers=headers) as session:
        async with session.get(url,headers=headers) as response:
            response = await response.text()
            print(response)
            return response
asyncio.run(fetch(url))
```

**Comment by romis2012** [comment]
All proxy types that we support transmit whole TCP traffic. Your problem is something else.

**Comment by victor-ab** [comment]
Then why `connector=None` works and `connector=connector` does not? 
Any ideas on how to debug it?
I also tested the same request using `urllib`, which worked.

**Comment by romis2012** [comment]
All supported proxies (socks5, socks4, http tunnel) transmit _whole_ TCP traffic, otherwise they don't work

**Comment by victor-ab** [comment]
OK, will investigate it further. Thanks for the support!
