### ISSUE TITLE
how to connect to a proxy without url and use proxy ip and port only instead

### ISSUE THREAD

**Issue by cwz6h** [romis2012/aiohttp-socks#34]

**Comment by romis2012** [comment]
```python
from aiohttp_socks import ProxyType, ProxyConnector

connector = ProxyConnector(
      proxy_type=ProxyType.SOCKS5,
      host='127.0.0.1',
      port=1080,
      username='user',
      password='password',
      rdns=True
)
```

**Comment by cwz6h** [comment]
uh, so then what do I do with the variable?

**Comment by romis2012** [comment]
```python
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get(url) as response:
            return await response.text()
```

**Comment by cwz6h** [comment]
> ```python
>     async with aiohttp.ClientSession(connector=connector) as session:
>         async with session.get(url) as response:
>             return await response.text()
> ```

Uh Hey! Did You Read The Title Of This Issue? I Want To Connect To A Proxy Without A Url

**Comment by romis2012** [comment]
...and what's the problem?

**Comment by cwz6h** [comment]
> ...and what's the problem?

I want to connect to a proxy without url

**Comment by romis2012** [comment]
read my posts above, everything is written there
