### ISSUE TITLE
no proxytimeout

### ISSUE THREAD

**Issue by MHProDev** [romis2012/aiohttp-socks#35]
![image](https://user-images.githubusercontent.com/63018646/178955905-64a58d78-64e2-4956-a9b5-d71e36152473.png)
![image](https://user-images.githubusercontent.com/63018646/178955984-5f950ad9-b057-4b32-ab76-1a92ed06ebcd.png)
![image](https://user-images.githubusercontent.com/63018646/178956079-1a344769-ff2c-4fff-b85e-298d5b5309dc.png)

unable to settimeout for proxy connection workers got freeze

**Comment by romis2012** [comment]
`open_connection` and `create_connection` are deprecated, use [python-socks](https://github.com/romis2012/python-socks) instead
