### ISSUE TITLE
Access remote server IP when accessed through SOCKS proxy

### ISSUE THREAD

**Issue by weimdall** [romis2012/aiohttp-socks#39]
Hello,

I need to get the IP of the remote server,
without the proxy lib I would use `response.connection.transport.get_extra_info("peername")` 
But when using the proxy, that returns me the IP of the proxy server (which is expected, since the TCP Connection is going though it)

Despite reading pages of documentation,
I did not find proper solution to obtain the IP that has been resolved through the SOCKS5 proxy.
Can someone give me a clue about where to look ?

## Code sample
Without proxy :
```python
async def fetch(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            peer_ip, peer_port = response.connection.transport.get_extra_info("peername")
            # peer_ip contains remote server IP
            return await response.text()
```

With SOCKS5 proxy :
```python
async def fetch(url):
    connector = ProxyConnector.from_url('socks5://user:password@127.0.0.1:1080')
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get(url) as response:
            peer_ip, peer_port = response.connection.transport.get_extra_info("peername")
            # peer_ip contains SOCKS server IP - how to obtain remote server IP from here ?
            return await response.text()
```

**Comment by romis2012** [comment]
> ...But when using the proxy, that returns me the IP of the proxy server...

This is the expected behavior since you are connecting to a proxy server and not to the target host

> I did not find proper solution to obtain the IP that has been resolved through the SOCKS5 proxy

In general, there is no way to obtain remote ip from a proxy

**Comment by weimdall** [comment]
Thank you, that's exactly what I was looking for.
I assume the host resolution would then be done using the cached DNS values (when enabled) ?

For the records, here is a working solution :
```python
async def fetch(url, connector=None):
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get(url) as response:
            if self._connector is not None:
                addrinfo = await response.connection.loop.getaddrinfo(response.host, None)
                peer_ip = addrinfo[0][4][0]
            else:
                peer_ip, peer_port = response.connection.transport.get_extra_info("peername")
            return await response.text()

fetch("http://test.com")
fetch("http://test.com", ProxyConnector.from_url('socks5://user:password@127.0.0.1:1080'))
```
