### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by ap-leemurus** [romis2012/aiohttp-socks#41]
Sample https://github.com/Slzdude/aiohttp-proxy

Problem with asyncio `TLS in TLS` was fixed https://bugs.python.org/issue37179

**Comment by romis2012** [comment]
https://github.com/romis2012/aiohttp-socks/issues/37#issuecomment-1443689753

**Comment by ap-leemurus** [comment]
@romis2012 
No:
1. https://github.com/romis2012/aiohttp-socks/blob/master/aiohttp_socks/connector.py#L105C36-L105C36
2. https://github.com/romis2012/python-socks/blob/master/python_socks/_helpers.py#L57

Now only works HTTP proxies that add TLS for HTTP CONNECT.

**Comment by romis2012** [comment]
> ...HTTP proxies that add TLS for HTTP CONNECT...

Yes, they are exactly what "https proxy" is.

**Comment by ap-leemurus** [comment]
@romis2012 
But I can't use proxies with https://. Only http://proxy + https://website

**Comment by romis2012** [comment]
> But I can't use proxies with https://

Just use `http` scheme

**Comment by mjpieters** [comment]
> > But I can't use proxies with https://
> 
> Just use `http` scheme

No, because that's not HTTPS-over-HTTPS, that's a HTTP Proxy with CONNECT support to then forward the HTTPS connection.

I have proxies that **only** support HTTPS-over-HTTPS, which can't be used with a http scheme. Please implement HTTPS-over-HTTPS. 

What ever came of romis2012/python-socks#10?

**Comment by romis2012** [comment]
> ...HTTPS-over-HTTPS...

You should pass `proxy_ssl` parameter to ProxyConnector constructor
