### ISSUE TITLE
aiohttp 3.10.0 may have broken ProxyConnector implementation?

### ISSUE THREAD

**Issue by vEpiphyte** [romis2012/aiohttp-socks#43]
The happyeyeballs support ( added here https://github.com/aio-libs/aiohttp/commit/1700e9d62e38591f0d094a8ebb8b54d1f22b9044 https://github.com/aio-libs/aiohttp/pull/7954 https://github.com/aio-libs/aiohttp/pull/8005 ) changed the call signature of the `TCPConnector._wrap_create_connection` function.

Using a proxy like this in aiohttp 3.9.5 would result in a timeout when connecting.
```
proxy='socks5://user:pass@127.0.0.1:1'  # Example proxy value that would previously timeout connecting
connector = aiohttp_socks.ProxyConnector.from_url(proxy)
async with aiohttp.ClientSession(connector=connector) as sess:
    async with sess.request('GET', url) as resp:
        # do stuff with response
```

In aiohttp 3.10.0 this now raises a TypeError:

```
Traceback (most recent call last):
  File "/some/path/file.py", line 1729, in foo
    async with sess.request('GET', url) as resp:
  File "/some/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1344, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/aiohttp/client.py", line 648, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 546, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 954, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1282, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ProxyConnector._wrap_create_connection() missing 2 required positional arguments: 'host' and 'port'
```

**Comment by romis2012** [comment]
Fixed in v0.9.0

**Comment by vEpiphyte** [comment]
@romis2012 Thanks! I missed that - I thought I had installed the latest aiohttp-socks when I was testing. I'll go ahead and close this.

**Comment by thecockatiel** [comment]
Hi @romis2012 
is there any way we get support for older versions automatically?
or are you open to such PRs ?

**Comment by romis2012** [comment]
@thecockatiel 
`aiohttp-socks<0.9` is compatible with `aiohttp<3.10.0` and
`aiohttp-socks>=0.9` is compatible with `aiohttp>=3.10.0`

**Comment by thecockatiel** [comment]
why not make all versions compatible ?
it's pretty easy
I'll send a PR soon, maybe you like how small the needed change is

**Comment by romis2012** [comment]
> why not make all versions compatible ?

Because there's no need for that.

> I'll send a PR soon, maybe you like how small the needed change is

The PR will be rejected.  Don't waste your time.

**Comment by thecockatiel** [comment]
Well, here's a bit of context, but it's okay if you still don't like it and want to reject:
I am working on a project, which aims to be able to run on debian bullseye without the need to install packages outside of the ones the repository provides, which means the aiohttp version there will be old
aiohttp-socks is missing there, so I have included the project in my source directly
I work on different machines and the one I use have modern packages
so just switching to the debian breaks the project

hence this suggestion

It was a very small change, but It's okay if you don't want it. thanks for creating this useful lib :)

**Comment by romis2012** [comment]
@thecockatiel 
just use `aiohttp-socks==0.8.*`

**Comment by thecockatiel** [comment]
It's okay
I mean all versions is unrealistic, but supporting more versions is nice, but it's just "nice"

as I have said before, thanks for creating this useful lib, 
even if this change is not good enough to make it in the official repo, the patch certainly helps me as I have copied the files in my project

so no worries
