### ISSUE TITLE
pypi is missing tests

### ISSUE THREAD

**Issue by jirislaby** [romis2012/aiohttp-socks#9]
Could you add tests to the pypi package too, so that we can run the tests on the distribution side?

**Comment by romis2012** [comment]
It's not a good idea to add tests to the package because it

1. violates python packaging guidelines (see https://packaging.python.org/, https://github.com/pypa/sampleproject)

2. requires additional dependencies including 3proxy binary distributions

**Comment by romis2012** [comment]
You can clone the repository and run tests at any time
